### DISCUSSION TITLE
Use fixed arrow version rather than flexible arrow version.

### DISCUSSION THREAD

**Discussion by liurenjie1024** [icelake-io/icelake#234] [Ideas]
Currently in icelake, we use following format to specify arrow version:
```
arrow = { version = ">= 46"}
```

This may cause some problems since arrow doesn't guarantee compatibility in upgrading major version. For example, it will make icelake unable to compile when user specifies a higher version such as 48, which makes this range version meaningless.

cc @Xuanwo @ZENOTME

**Comment by Xuanwo** [comment]
The main issue we're facing is supporting users with varying arrow versions. This becomes more complicated for icelake, as it uses arrow for both input and output types, preventing us from simply allowing arrow 46 & 47 to coexist simultaneously. Users' additional components may need the use of arrow 46 types.

To further complicate matters, all arrow components released under the same major version. For instance:

```toml
arrow = { version = "47.0.0", features = ["pyarrow"] }
arrow-select = { version = "47.0.0" }
arrow-array = { version = "47.0.0" }
arrow-buffer = { version = "47.0.0" }
arrow-flight = { version = "47.0.0", features = ["flight-sql-experimental", "tls"] }
arrow-ipc = { version = "47.0.0" }
arrow-schema = { version = "47.0.0", features = ["serde"] }
arrow-ord = { version = "47.0.0" }
arrow-cast = { version = "47.0.0", features = ["prettyprint"] }
parquet = { version = "47.0.0", features = ["async"] }
parquet_rs = { package = "parquet", version = "47.0.0" }
arrow-format = { version = "0.8.1", features = ["flight-data", "flight-service", "ipc"] }
```

A potential solution could be to implement feature gates that support the latest three versions of arrow, but this might significantly increase our workload. And I'm not sure if this works.
